server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
  datasource:
    url: jdbc:mysql://localhost:3306?seata_order
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234561

feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*xml

