server:
  port: 80

spring:
  application:
    name: cloud-order-feign-service

eureka:
  client:
    # true表示将自己注册进Eureka Server，默认为true
    register-with-eureka: true
    # 是否从Eureka Server抓取以有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka

# 设置feign客户端超时时间（OpenFeign默认支持Ribbon）
ribbon:
  # 指的是建立连接后从服务器读取到可用资源所用时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志已什么级别监控哪个接口
    ink.bignose.springcloud.service.PaymentFeignService: debug